### ISSUE TITLE
json is required gem

### ISSUE THREAD

**Issue by duplabe** [ruhoh/ruhoh.rb#4] opened 2012-04-04 19:19 UTC
I followed the install steps. After running ruhoh new site_name I had an error:

<code>/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- json (LoadError)</code>

After I installed json gem the error disappeared.

**Comment by plusjade** [comment] 2012-05-13 09:21
I'm going to close this because I have not being able to reproduce it on my osx lion and ubuntu 10.4. That's not to say it's not a problem, but I have no way to troubleshoot the issue. If more users experience the problem, we'll get some more tickets.

Oh, p.s. now I know why it took me so long to reply. It looks like you are runing ruby 1.8. ruhoh does not officially support 1.8

**Closed as completed by plusjade** 2012-05-13 09:21 UTC
Labels: bug
